Repository ContentGraz/dita-ot-docs, pull requests merged in 2018-04, with the labels that each got.

#4 Add index entries to preprocessing topics
  reference/preprocess-chunk.dita
  reference/preprocess-conref.dita
  reference/preprocess-metadata.dita
  reference/preprocess-profile.dita
  reference/preprocess-topic-fragment.dita
Labels: IA-group-5

#5 Add index terms for cos17 2nd e-tivity
  reference/preprocess-debugfilter.dita
Labels: IA-group-4

#6 Add index terms for cos17 2nd e-tivity
  reference/preprocess-mapref.dita
Labels: IA-group-4

#7 Add index terms for cos17 2nd e-tivity
  reference/preprocess-branch-filter.dita
Labels: IA-group-4

#8 Add index terms for cos17 2nd e-tivity
  reference/preprocess-copyfiles.dita
Labels: IA-group-4

#9 Committen mit oXygen XML Web Author
  reference/preprocess-keyref.dita
Labels: IA-group-4

#10 Add index terms for cos17 2nd e-tivity
  reference/preprocess-copy-to.dita
Labels: IA-group-4

#49 Cos17 philantrop22
  reference/preprocess-branch-filter.dita
  reference/preprocess-copy-to.dita
  reference/preprocess-copyfiles.dita
  reference/preprocess-debugfilter.dita
  reference/preprocess-keyref.dita
  reference/preprocess-mapref.dita
Labels: IA-group-4

#26 Committing with oXygen XML Web Author
  index.dita
Labels: IA-group-1

#27 Committing with oXygen XML Web Author
  release-notes/index.dita
Labels: IA-group-1

#50 Cos17 alexflags
  index.dita
  release-notes/index.dita
  topics/determining-version-of-ditaot.dita
  topics/installing-client.dita
  topics/prerequisite-software.dita
  topics/using-dita-command.dita
Labels: IA-group-1

#32 inserted keywords/indexes for XHTML processing
  reference/XhtmlDefault.dita
Labels: IA-group-5

#38 inserted keywords/indexes for eclipse help processing
  reference/XhtmlEclipse.dita
Labels: IA-group-5

#42 inserted keywords/indexes for TocJS processing
  reference/XhtmlTocjs.dita
Labels: IA-group-5

#43 inserted keywords/indexes for HTML help processing
  reference/XhtmlCHM.dita
Labels: IA-group-5

#51 Cos17 aloisia2211
  reference/XhtmlCHM.dita
  reference/XhtmlDefault.dita
  reference/XhtmlEclipse.dita
  reference/XhtmlTocjs.dita
  reference/html5.dita
Labels: IA-group-5

#36 Maplink index terms done
  reference/preprocess-maplink.dita
Labels: IA-group-5

#40 Topicpull index terms done
  reference/preprocess-topicpull.dita
Labels: IA-group-5

#44 Flagging index terms done
  reference/preprocess-flagging.dita
Labels: IA-group-5

#45 HTML-based processing modules index terms done
  reference/XhtmlWithNavigation.dita
Labels: IA-group-5

#46 Common HTML-based processing index terms done
  reference/XhtmlCommon.dita
Labels: IA-group-5

#47 Map cleanup index terms done
  reference/preprocess-clean-map.dita
Labels: IA-group-5

#14 Added dita command index entry.
  parameters/generate-copy-outer.dita
Labels: IA-group-2

#15 Added dita command index entry.
  topics/html-customization-properties-file.dita
Labels: IA-group-2

#16 Added dita command index entry.
  topics/html-customization-plugins.dita
Labels: IA-group-2

#17 Added dita command index entry.
  topics/html-customization-plugin-bundle-css.dita
Labels: IA-group-2

#18 Added dita command index entry.
  topics/pdf-customization.dita
Labels: IA-group-2

#53 Cos17 melanie137
  parameters/generate-copy-outer.dita
  topics/html-customization-header.dita
  topics/html-customization-plugin-bundle-css.dita
  topics/html-customization-plugins.dita
  topics/html-customization-properties-file.dita
  topics/pdf-customization.dita
Labels: IA-group-2

#33 Added index terms
  topics/migration.dita
Labels: IA-group-3

#34 Added index terms
  topics/migrating-to-3.0.dita
Labels: IA-group-3

#35 Added index terms
  topics/migrating-to-2.5.dita
Labels: IA-group-3

#37 Added index terms
  topics/migrating-to-2.4.dita
Labels: IA-group-3

#39 Added index terms
  topics/migrating-to-2.3.dita
Labels: IA-group-3

#41 Added index terms
  topics/migrating-to-2.2.dita
Labels: IA-group-3

#54 Cos17 lexe07
  topics/migrating-to-2.2.dita
  topics/migrating-to-2.3.dita
  topics/migrating-to-2.4.dita
  topics/migrating-to-2.5.dita
  topics/migrating-to-3.0.dita
  topics/migration.dita
Labels: IA-group-3

#19 Index for "Alternative authoring formats"
  topics/alternative-input-formats.dita
Labels: IA-group-1

#20 Indexterms for markdown content
  topics/markdown-input.dita
Labels: IA-group-1

#21 Indexterms for Preview Support for Lightweights DITA
  topics/lwdita-input.dita
Labels: IA-group-1

#22 Indexterms for Markdown DITA syntax
  topics/markdown-dita-syntax-reference.dita
Labels: IA-group-1

#23 Indexterms for building output
  topics/building-output.dita
Labels: IA-group-1

#24 Indexterms for Building output using the dita command:
  topics/using-dita-command.dita
Labels: IA-group-1

#55 Cos17 xeniana
  topics/alternative-input-formats.dita
  topics/building-output.dita
  topics/lwdita-input.dita
  topics/markdown-dita-syntax-reference.dita
  topics/markdown-input.dita
  topics/using-dita-command.dita
Labels: IA-group-1

#58 Added the following index terms to the keywords: + release 1.5.4 + DITA-OT 1.5.4
  topics/migrating-to-1.5.4.dita
Labels: IA-group-4

#59 Added the following index terms to the keywords: + log files + DITA-OT error messages + How can I access help for the dita command? + how to enable debug mode + enable debug mode + increase Java memory allocation + reduce processing time
  topics/troubleshooting-overview.dita
Labels: IA-group-4

#60 Added the following index terms to the keywords: + Ant + <>dita<> command + AnsiColorLogger
  topics/log-files.dita
Labels: IA-group-4

#61 Added the following index terms to the keywords: + Out of memory error + UnsupportedClassVersionError + Unable to locate tools.jar
  topics/other-errors.dita
Labels: IA-group-4

#11 Comitten with Oxygen
  topics/dita2tocjs.dita
Labels: IA-group-1, additional-commits

#68 Cos17 silvia174
  parameters/dita-command-arguments.dita
  parameters/index.dita
  topics/dita2dita.dita
  topics/dita2tocjs.dita
  topics/dita2troff.dita
  topics/dita2xhtml.dita
Labels: IA-group-1

#69 Cos17 sarolta82
  topics/log-files.dita
  topics/migrating-to-1.5.4.dita
  topics/other-errors.dita
  topics/troubleshooting-overview.dita
Labels: IA-group-4

#76 Cos17 philipp reiber
  topics/ant.dita
  topics/creating-an-ant-build-script.dita
  topics/migrating-ant-to-dita.dita
  topics/publishing-with-ant.dita
  topics/using-dita-properties-file.dita
Labels: IA-group-1

#77 Index Keywords added.
  parameters/internal-ant-properties.dita
Labels: IA-group-2, additional-commits

#78 Added Index Keywords.
  topics/extending-the-ot.dita
Labels: IA-group-2, additional-commits

#82 Committen mit oXygen XML Web Author
  topics/html-customization-navigation.dita
Labels: IA-group-2, additional-commits

#83 Cos17 joschak
  topics/html-customization-navigation.dita
  topics/html-customization-parameters.dita
Labels: IA-group-2

#103 Cos17 bauersteph
  reference/flagging-migration.dita
  topics/migrating-to-1.6.dita
  topics/migrating-to-1.7.dita
  topics/migrating-to-1.8.dita
  topics/migrating-to-2.0.dita
  topics/migrating-to-2.1.dita
Labels: IA-group-4

#57 Add index terms for cos17 e-tivity 2
  topics/enabling-debug-mode.dita
Labels: IA-group-4, additional-commits

#109 Cos17 ninahint
  reference/architecture.dita
  reference/index.dita
  topics/dita-command-help.dita
  topics/enabling-debug-mode.dita
  topics/increasing-the-jvm.dita
  topics/reducing-processing-time.dita
Labels: IA-group-4

#117 Cos17 vic cos17
  topics/custom-plugins.dita
  topics/globalization-languages.dita
  topics/globalization-support.dita
  topics/globalization.dita
  topics/plugin-addgeneratedtext.dita
  topics/plugins-installing.dita
Labels: IA-group-2

#116 Add index terms for COS17 e-tivity2
  extension-points/plugin-extension-points-general.dita
Labels: additional-commits

#122 Cos17 berndwalter1980
  extension-points/extension-points-by-plugin.dita
  extension-points/plugin-extension-points-general.dita
  extension-points/plugin-extension-points-support.dita
  extension-points/plugin-extension-points-xslt-import.dita
  extension-points/plugin-extension-points-xslt-parameters.dita
Labels: IA-group-3, additional-commits

#123 Removing plugins
  topics/plugins-removing.dita
Labels: IA-group-3

#129 Plug-in dependencies
  topics/plugin-dependencies.dita
Labels: IA-group-3

#132 BM entries for Plug-in descriptor file
  topics/plugin-configfile.dita
Labels: IA-group-3

#133 BM entries for plugin-xmlcatalog.dita
  topics/plugin-xmlcatalog.dita
Labels: IA-group-3

#135 Cos17 diebabsi
  topics/plugin-applications.dita
  topics/plugin-configfile.dita
  topics/plugin-dependencies.dita
  topics/plugin-xmlcatalog.dita
  topics/plugins-removing.dita
Labels: IA-group-3

#134 Cos17 joschak redux2
  parameters/internal-ant-properties.dita
  topics/extending-the-ot.dita
  topics/html-customization-css.dita
  topics/html-customization-navigation.dita
  topics/html-customization-parameters.dita
  topics/html-customization.dita
Labels: IA-group-2

#124 Added index-terms
  topics/plugin-antpreprocess.dita
Labels: IA-group-3

#125 Added index-terms
  topics/plugin-newtranstype.dita
Labels: IA-group-3

#126 Added index-terms
  topics/using-plugin-URI-extension.dita
Labels: IA-group-3

#127 Added index-terms
  topics/plugin-xsltparams.dita
Labels: IA-group-3

#128 Added index-terms
  topics/plugin-javalib.dita
Labels: IA-group-3

#131 EP entries for plugin-overridestyle.dita
  topics/plugin-overridestyle.dita
Labels: IA-group-3

#138 Cos17 gena3004
  topics/plugin-antpreprocess.dita
  topics/plugin-javalib.dita
  topics/plugin-newtranstype.dita
  topics/plugin-overridestyle.dita
  topics/plugin-xsltparams.dita
  topics/using-plugin-URI-extension.dita
Labels: IA-group-3

#144 Committing with oXygen XML Web Author
  topics/plugin-sample.dita
Labels: IA-group-3

#145 Committing with oXygen XML Web Author
  topics/plugin-best-practices.dita
Labels: IA-group-3

#148 Committing with oXygen XML Web Author
  extension-points/plugin-extension-points.dita
Labels: IA-group-3

#149 Cos17 michaelstangl
  extension-points/plugin-extension-points.dita
  topics/plugin-best-practices.dita
  topics/plugin-messages.dita
  topics/plugin-newextensions.dita
  topics/plugin-sample.dita
Labels: IA-group-3

#136 Add index terms for cos17 e-tivity2
  topics/output-formats.dita
Labels: IA-group-1

#137 Add index terms for cos17 e-tivity 2
  topics/dita2pdf.dita
Labels: IA-group-1

#140 Add index terms for cos17 e-tivity 2
  topics/dita2eclipsehelp.dita
Labels: IA-group-1

#142 Add index terms for cos17 e-tivity 2
  topics/dita2htmlhelp.dita
Labels: IA-group-1

#147 Add index terms for cos17 e-tivity 2
  topics/dita2markdown.dita
Labels: IA-group-1

#150 Cos17 leticiaschmiedc
  topics/dita2eclipsehelp.dita
  topics/dita2htmlhelp.dita
  topics/dita2markdown.dita
  topics/dita2pdf.dita
  topics/output-formats.dita
Labels: IA-group-1

#151 Added index terms for #cos17 e-tivity № 2.
  reference/pdf-transform.dita
Labels: IA-group-5

#152 Added index terms for #cos17 e-tivity № 2.
  reference/pdf-transformation-history.dita
Labels: IA-group-5

#153 Added index terms for #cos17 e-tivity № 2.
  reference/DITA_spec-support.dita
Labels: IA-group-5

#154 Added index terms for #cos17 e-tivity № 2.
  reference/DITA_v1-2-support.dita
Labels: IA-group-5

#155 Added index terms for #cos17 e-tivity № 2.
  reference/DITA_v1-3-support.dita
Labels: IA-group-5

#156 Added index terms for #cos17 e-tivity № 2.
  reference/implementation-dependent-features.dita
Labels: IA-group-5

#158 Cos17 maticmol
  reference/DITA_spec-support.dita
  reference/DITA_v1-2-support.dita
  reference/DITA_v1-3-support.dita
  reference/implementation-dependent-features.dita
  reference/pdf-transform.dita
  reference/pdf-transformation-history.dita
Labels: IA-group-5

#157 Etivity 2 Cos 17 FH Joanneum
  parameters/parameters_intro.dita
Labels: IA-group-2, additional-commits

#159 Etivity 2 Cos 17 FH Joanneum
  parameters/parameters-other.dita
Labels: IA-group-2

#160 Etivity 2 Cos 17 FH Joanneum
  parameters/configuration-properties.dita
Labels: IA-group-2

#161 Etivity 2 Cos 17 FH Joanneum
  parameters/local-properties.dita
Labels: IA-group-2

#162 Etivity 2 Cos 17 FH Joanneum
  parameters/lib-plugin-properties.dita
Labels: IA-group-2

#163 Etivity 2 Cos 17 FH Joanneum
  parameters/lib-configuration-properties.dita
Labels: IA-group-2

#164 Cos17 katrinburgstaller 2
  parameters/configuration-properties.dita
  parameters/lib-configuration-properties.dita
  parameters/lib-plugin-properties.dita
  parameters/local-properties.dita
  parameters/parameters-other.dita
  parameters/parameters_intro.dita
Labels: IA-group-2

#166 add index terms for cos 17 Etivity n°2
  reference/extended-functionality.dita
Labels: IA-group-5

#167 add index terms for cos 17 Etivity n°2
  reference/DITA-features-in-docs.dita
Labels: IA-group-5

#168 add index terms for cos 17 Etivity n°2
  reference/java-api.dita
Labels: IA-group-5

#169 add index terms for cos 17 Etivity n°2
  reference/license.dita
Labels: IA-group-5

#170 add index terms for cos 17 Etivity n°2
  reference/third-party-software.dita
Labels: IA-group-5

#165 add index terms for cos 17 Etivity n°2
  topics/dita-and-dita-ot-resources.dita
Labels: IA-group-5, additional-commits

#171 Cos17 lizalezley
  reference/DITA-features-in-docs.dita
  reference/extended-functionality.dita
  reference/java-api.dita
  reference/license.dita
  reference/third-party-software.dita
  topics/dita-and-dita-ot-resources.dita
Labels: IA-group-5

#172 Committen mit oXygen XML Web Author
  reference/processing-structure.dita
Labels: IA-group-4

#173 Commiting
  reference/map-first-preprocessing.dita
Labels: IA-group-4

#174 Committen mit oXygen XML Web Author
  reference/processing-pipeline-modules.dita
Labels: IA-group-4

#175 Committen mit oXygen XML Web Author
  reference/preprocessing.dita
Labels: IA-group-4

#176 Committen mit oXygen XML Web Author
  reference/preprocess-genlist.dita
Labels: IA-group-4
